name: meoscleanarchitecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.3.3
  intl: ^0.19.0
  fpdart: ^1.1.0
  get_it: ^7.7.0
  hive: ^4.0.0-dev.2
  image_picker: ^1.1.1
  flutter_bloc: ^8.1.5
  dotted_border: ^2.1.0
  path_provider: ^2.1.0
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.2
  isar_flutter_libs: ^4.0.0-dev.13
  internet_connection_checker_plus: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
