name: meoscleanarchitecture
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.5
  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
